name: Sync Examples 
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@2.0.0
        with:
          readme-oas-key: ${{ secrets.README_EXAMPLES_SECRET }} 
          oas-file-path: './examples.json'
          api-version: 'v1.0.0'
