name: Sync OAS to ReadMe (multiple versions)
on:
  push:
    branches:
      - main
      - next
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: readmeio/rdme@7.0.3
        with:
          rdme: openapi ./petstore-1.0.json --key=${{ secrets.README_OAS_KEY }} --id=624c6b4fc1cefd01565cd68b
          rdme: openapi ./petstore-2.0.json --key=${{ secrets.README_OAS_KEY }} --id=624c76a0c1eec3003ecf8b22
